version: '3'

networks:
  intelmq-network:
    driver: bridge

services:
  intelmq:
    build: intelmq/
    depends_on:
      - ubuntu
      - redis
    image: intelmq
    restart: "no"
    logging:
      driver: syslog
    networks:
      - intelmq-network
    links:
      - redis

  redis:
    image: redis
    build: redis/
    restart: "always"
    depends_on:
      - ubuntu
    networks:
      - intelmq-network

  ubuntu:
    build: ubuntu/
    image: ubuntu:latest

